# Generated by Django 5.0.3 on 2025-10-05 14:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Ambiente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do Orçamento')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDO', 'Concluído')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Componente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Peça')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Peça',
                'verbose_name_plural': 'Tipos de Peças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Móvel')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveis', to='marcenaria.ambiente', verbose_name='Ambiente')),
            ],
            options={
                'verbose_name': 'Móvel',
                'verbose_name_plural': 'Móveis',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ambiente',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='marcenaria.orcamento', verbose_name='Orçamento'),
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Bruto')),
                ('preco_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Líquido')),
                ('unidade_medida', models.CharField(choices=[('LINEAR', 'Metro Linear (m)'), ('QUADRADO', 'Metro Quadrado (m²)'), ('UNIDADE', 'Unidade (un)')], default='UNIDADE', max_length=10, verbose_name='Unidade de Medida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marcenaria.fornecedor', verbose_name='Fornecedor')),
                ('tipo_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.tipocomponente', verbose_name='Tipo de Componente')),
            ],
            options={
                'verbose_name': 'Componente (Material)',
                'verbose_name_plural': 'Componentes (Materiais)',
                'ordering': ['tipo_componente__nome'],
            },
        ),
    ]
