# Generated by Django 5.0.3 on 2025-10-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_calculo', models.JSONField(help_text='Dados específicos como altura, largura, etc.', verbose_name='Dados do Cálculo')),
                ('quantidade_calculada', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade Calculada')),
                ('unidade', models.CharField(default='m²', max_length=20, verbose_name='Unidade')),
                ('resumo_calculo', models.TextField(verbose_name='Resumo do Cálculo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcenaria.componente', verbose_name='Componente Utilizado')),
                ('movel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='marcenaria.movel')),
                ('tipo_peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcenaria.tipopeca', verbose_name='Tipo de Peça')),
            ],
            options={
                'verbose_name': 'Peça do Orçamento',
                'verbose_name_plural': 'Peças do Orçamento',
            },
        ),
    ]
