# Generated by Django 5.0.3 on 2025-10-05 14:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Usar apenas para Metro Quadrado', max_digits=7, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='componente',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Usar apenas para Metro Linear', max_digits=7, null=True, verbose_name='Comprimento (m)'),
        ),
        migrations.AddField(
            model_name='componente',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Usar apenas para Metro Quadrado', max_digits=7, null=True, verbose_name='Largura (m)'),
        ),
        migrations.AddField(
            model_name='componente',
            name='profundidade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Usar apenas para Metro Quadrado', max_digits=7, null=True, verbose_name='Profundidade (m)'),
        ),
        migrations.AddField(
            model_name='componente',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Usar apenas para Unidades', verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='componente',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usar apenas para Líquidos', max_digits=8, null=True, verbose_name='Volume (ml)'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='preco_liquido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Líquido (por unidade de medida)'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='unidade_medida',
            field=models.CharField(choices=[('QUADRADO', 'Metro Quadrado (m²)'), ('LINEAR', 'Metro Linear (m)'), ('LIQUIDO', 'Mililitros (ml)'), ('UNIDADE', 'Unidade (un)')], default='UNIDADE', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
