# Generated by Django 5.0.3 on 2025-10-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0002_pecaorcamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PecaOrcamento',
        ),
    ]
