# Generated by Django 5.0.3 on 2025-10-05 15:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0002_componente_altura_componente_comprimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='preco_liquido',
        ),
        migrations.AddField(
            model_name='componente',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, help_text='Calculado automaticamente ao salvar', max_digits=10, verbose_name='Custo por m²/m/ml/unidade'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='preco_bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Preço total pago pelo componente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Bruto Total'),
        ),
    ]
