# Generated by Django 5.0.3 on 2025-10-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0003_remove_componente_preco_liquido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, help_text='Usar apenas para Unidades', null=True, verbose_name='Quantidade'),
        ),
    ]
