# Generated by Django 5.0.3 on 2025-10-05 18:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0003_delete_pecaorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='dados_orcamento',
            field=models.JSONField(blank=True, help_text='Estrutura completa do orçamento com ambientes, móveis, peças e cálculos', null=True, verbose_name='Dados do Orçamento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total calculado do orçamento', max_digits=12, verbose_name='Valor Total'),
        ),
    ]
