# Generated by Django 5.0.3 on 2025-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0004_alter_componente_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='nome',
            field=models.CharField(default='Componente sem nome', help_text="Nome específico deste componente (ex: 'Chapa MDF 18mm Branca 2,75x1,83m')", max_length=200, verbose_name='Nome do Componente'),
        ),
    ]
